[package]
name = "gta2_viewer"
version = "0.1.0"
authors = ["Hendrik Kunert <hendrik.kunert@henku.de>"]

[dependencies]
byteorder = "1"
ndarray = "0.16"

[dependencies.sdl2]
version = "0.33"
default-features = false
features = ["image"]
