[package]
name = "gta2_viewer"
version = "0.1.0"
authors = ["Hendrik Kunert <hendrik.kunert@henku.de>"]
edition = "2021"

[dependencies]
bevy = "0.15.1"
wgpu = { version = "23.0.1", default-features = false }
byteorder = "1"
ndarray = "0.16"

[dependencies.sdl2]
<<<<<<< HEAD
version = "0.33"
=======
version = "0.37"
>>>>>>> 2346cc8 (Add color lookup from palletes)
default-features = false
features = ["image"]
